config/routes.rb
Tweetful::Application.routes.draw do
  devise_for :users

  authenticated :user do
    resources :follows, :except => [:new, :edit, :show, :update]
    resources :tweets, :except => [:new, :edit, :show, :update]
    root :to => 'follows#index', :as => :user_root
  end

  root :to => 'home#index'

  get '/about' => 'about#index'
  get '/team' => 'team#index'
  

end

app/views/shared/_left_nav.html.erb
<ul>
  <li>
    <%= content_tag :strong, current_user.name %>
  </li>
  <li>
    <%= content_tag :small, '@'+current_user.username %>
  </li>
  <li>
    <table>
      <tbody>
        <tr>
          <td>
            <%= content_tag :h4, current_user.tweets.count %>
            <%= content_tag :small, 'Tweets', :class => "uppercase lighter" %>
          </td>
          <td>
            <%= content_tag :h4, current_user.follows.count %>
            <%= content_tag :small, 'Following', :class => "uppercase lighter" %>
          </td>
          <td>
            <%= content_tag :h4, Follow.where(:following_id => current_user.id).count %>
            <%= content_tag :small, 'Followers', :class => "uppercase lighter" %>
          </td>
      </tbody>
    </table>
  </li>
  <li>
    <%= form_for (@tweet || :tweet), :url => tweets_path,
                                     :builder => InlineErrorsBuilder,
                                     :method => :POST,
                                     :role => :form do |f| %>
      <div class="mar-top-15">
        <%= content_tag :div do %>
          <%= f.text_area :content, :placeholder => "Compose new Tweet..." %>
          <%= f.errors_for :content %>
        <% end %>

        <%= f.submit "Tweet" %>
      </div>
    <% end %>
  </li>
</ul>

<ul>
  <%= nav_item("Follow", follows_path) %>
  <%= nav_item("Tweet", tweets_path) %>
</ul>